### PR TITLE
ci: add bors and self-tests

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by wmww** [comment]
Hmm, looks good to me. Not sure why things are failing.

**Comment by Saviq** [comment]
@wmww that's what we need to work out - these are the kinds of environments we want to be running this in, so we need to make this solid.

One thing that can be seen now is that we're not getting enough feedback to see what could've gone wrong - like logs for either the server or the client on some tests.

https://github.com/lhotari/action-upterm/ can help debug this.

That said, we can merge yours, as it clearly works locally - and iterate on the CI side.

**Comment by Saviq** [comment]
@wmww we may need to work around this for now https://github.com/MirServer/mir/issues/2799#issuecomment-1441776216

**Comment by Saviq** [comment]
bors try

@wmww this is ready to go

**Review by wmww — APPROVED** [review]
LGTM bors r+

**Pull request merged**
