### PR TITLE
snaps: refresh snap lists

### PR DESCRIPTION
**Pull request by Saviq**
Snaps with 20/, 22/ tracks:
- ubuntu-frame
- ubuntu-frame-osk
- ubuntu-frame-vnc
- mir-test-tools
- graphics-test-tools

Snaps moving over to 22.04:
- confined-shell

Snaps remaining on 20.04:
- mir-kiosk
- mir-kiosk-kodi
- mir-kiosk-scummvm
- mir-kiosk-neverputt
- mir-kiosk-x11
- egmde
- mircade

### CODE REVIEW

**Review by AlanGriffiths — APPROVED** [review]
LGTM

bors merge

**Comment by Saviq** [comment]
bors r=AlanGriffiths

**Comment by Saviq** [comment]
Grh.

bors retry

**Comment by Saviq** [comment]
Tracks now in place.

bors retry

**Comment by Saviq** [comment]
bors r=AlanGriffiths

**Comment by Saviq** [comment]
And all recipes in place now, too.

bors r=AlanGriffiths

**Pull request merged**
