### PR TITLE
ci: add base bandwidth scenarios

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by wmww** [comment]
Looks good, one concern I have is that the exact screencopy usage might be dependent on installed font or other qterminal configuration details.

**Comment by Saviq** [comment]
> Looks good, one concern I have is that the exact screencopy usage might be dependent on installed font or other qterminal configuration details.

Sure, but the idea is to monitor this over time on the same environment, not compare between different environments.

**Comment by Saviq** [comment]
OK @wmww I'm done with this, it's 10pm here so I might've gone off the edge somewhere ;)

**Review by wmww — APPROVED** [review]
LGTM

**Comment by wmww** [comment]
I keep forgetting if we have bors on this one

bors r+

**Pull request merged**
